### ISSUE TITLE
Improve footprint calculation

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#27]
Picking up from https://github.com/mojodna/marblecutter/issues/16 it appears that footprints are "dirty" and wrap around 180° to span the globe.

In https://github.com/mojodna/marblecutter/issues/16#issuecomment-316266813 @mojodna tried calculating these via GRASS and we get "cleaner" footprints (unclear about the 180° wrap, though – if not we can create a new issue for that).

This issue covers applying the GRASS fix into the transcoding workflow.

**Comment by nvkelso** [comment]
@iandees do you need anything more from Seth to add this logic to the code and Docker container requirements?

**Comment by iandees** [comment]
Not at this point. I'm presently working on adding GRASS to the Docker image.

**Comment by iandees** [comment]
An update here: turns out we don't need GRASS. We can do what GRASS is doing with `gdalwarp` and `rio shapes` as suggested by @mojodna. For example:

```
info=$(rio info N43W071.tif)
gdalwarp -r average -ts $[$(jq -r .width <<< $info) / 100] $[$(jq -r .height <<< $info) / 100] -srcnodata $(jq -r .nodata <<< $info) N43W071.tif N43W071_small.tif
rio shapes --mask --as-mask N43W071_small.tif > N43W071_small.json
```

I'm currently working this into the existing image/script.

I'm also trying to convert the multiple `Polygon` GeoJSON features that `rio shapes` generates into a single `MultiPolygon` so that our database is even cleaner ✨ .

**Comment by iandees** [comment]
Yep! I've reprocessed some of the data and footprints look way better so far:

![image](https://user-images.githubusercontent.com/261584/28418677-8ced6f86-6d2a-11e7-92b6-67d114b22a4f.png)
