### ISSUE TITLE
Recalculate existing footprints for cleaner output

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#28]
Following up from https://github.com/mojodna/marblecutter/issues/27, once we have a better method to calculate the footprints let's regenerate them.

- [x] Update transcoding logic to optionally only generate footprints, covered in https://github.com/mojodna/marblecutter/issues/29.
- [x] improved footprint polygons https://github.com/mojodna/marblecutter/issues/27.
- [x] Preserve existing min_zoom and priority curation on existing footprints for new footprints of the same IDs.

**Comment by nvkelso** [comment]
Since we're ending up with (new) default curation values for `min_zoom` and `max_zoom` please also regenerate the table from https://github.com/mojodna/marblecutter/issues/17#issuecomment-315401103 so we can compare (with https://github.com/mojodna/marblecutter/issues/17#issuecomment-315419423 applied) and look for discrepancies.

**Comment by iandees** [comment]
Here's where we're at right now. Note that the "count" is significantly lower because each source image will only show up once (as a multipolygon) rather than multiple rows, each with a single polygon.

|        source        | count | min_zoom | max_zoom | res  |
|----------------------|-------|----------|----------|------|
| etopo1               |     1 |        0 |       15 | 1853 |
| gmted                |    12 |        4 |       20 |  927 |
| gmted                |    96 |        6 |       20 |  232 |
| nrcan_cdem           |     2 |        7 |       20 |   93 |
| nrcan_cdem           |     2 |        7 |       20 |   92 |
| nrcan_cdem           |     9 |        7 |       20 |   84 |
| mgg_greatlakes       |     8 |        8 |       20 |   93 |
| nrcan_cdem           |     1 |        8 |       20 |   40 |
| nrcan_cdem           |     3 |        8 |       20 |   46 |
| nrcan_cdem           |     1 |        8 |       20 |   68 |
| nrcan_cdem           |   120 |        8 |       20 |   43 |
| nrcan_cdem           |    12 |        8 |       20 |   41 |
| nrcan_cdem           |     6 |        8 |       20 |   45 |
| nrcan_cdem           |     9 |        8 |       20 |   44 |
| eudem                |    80 |        9 |       20 |   31 |
| nrcan_cdem           |   857 |        9 |       20 |   23 |
| nrcan_cdem           |     6 |        9 |       20 |   37 |
| srtm                 | 14297 |        9 |       20 |   31 |
| austria              |     1 |       10 |       20 |   10 |
| kartverket           |   255 |       10 |       20 |   10 |
| mgg_inundation_sandy |    57 |       10 |       20 |    3 |
| ned13                |  1262 |       10 |       20 |   10 |
| geoscience_au        |     3 |       11 |       20 |    5 |
| mx_lidar             |  2503 |       11 |       20 |    5 |
| nzlinz               |   115 |       11 |       20 |    8 |
| pgdc_5m              |  3818 |       11 |       20 |    5 |
| ned                  |  7919 |       12 |       20 |    3 |
| ned_topobathy        |    35 |       12 |       20 |    3 |
| uk_lidar             |  1518 |       13 |       20 |    2 |

**Comment by iandees** [comment]
I did notice that when `rio shapes` builds a polygon that crosses the antimeridian (as with `50N180W_20101117_gmted_mea075.tif`) PostGIS will refuse to import that polygon. I'm looking into a way to fix that.

**Comment by nvkelso** [comment]
The NRCAN data comes in at widely varying min_zoom but also for different cell sizes. Is the latitude a consideration in Mercator space?

**Comment by nvkelso** [comment]
Can you confirm the updates in https://github.com/mojodna/marblecutter/issues/17#issuecomment-315472675 were also re-applied here, and paste in new table result. Thanks!

**Comment by nvkelso** [comment]
(Lambda tiler is live against new tables so can test at-will.)

**Comment by iandees** [comment]
I ran the `UPDATE` statements from https://github.com/mojodna/marblecutter/issues/17#issuecomment-315472675 and https://github.com/mojodna/marblecutter/issues/17#issuecomment-315481199. The min/max zooms look like this now.

|        source        | count | min_zoom | max_zoom | res  |
|----------------------|-------|----------|----------|------|
| etopo1               |     1 |        0 |       15 | 1853 |
| gmted                |    11 |        4 |        8 |  927 |
| gmted                |    84 |        4 |       10 |  232 |
| nrcan_cdem           |     2 |        7 |       20 |   93 |
| nrcan_cdem           |     2 |        7 |       20 |   92 |
| nrcan_cdem           |     9 |        7 |       20 |   84 |
| srtm                 | 14297 |        7 |       20 |   31 |
| mgg_greatlakes       |     8 |        8 |       20 |   93 |
| nrcan_cdem           |     9 |        8 |       20 |   44 |
| nrcan_cdem           |     1 |        8 |       20 |   40 |
| nrcan_cdem           |    12 |        8 |       20 |   41 |
| nrcan_cdem           |     6 |        8 |       20 |   45 |
| nrcan_cdem           |     1 |        8 |       20 |   68 |
| nrcan_cdem           |     3 |        8 |       20 |   46 |
| nrcan_cdem           |   120 |        8 |       20 |   43 |
| eudem                |    80 |        9 |       20 |   31 |
| nrcan_cdem           |     6 |        9 |       20 |   37 |
| nrcan_cdem           |   856 |        9 |       20 |   23 |
| austria              |     1 |       10 |       20 |   10 |
| geoscience_au        |     3 |       10 |       20 |    5 |
| kartverket           |   255 |       10 |       20 |   10 |
| mgg_inundation_sandy |    57 |       10 |       20 |    3 |
| mx_lidar             |  2503 |       10 |       20 |    5 |
| ned                  |  7914 |       10 |       20 |    3 |
| ned13                |  1255 |       10 |       20 |   10 |
| nzlinz               |   115 |       10 |       20 |    8 |
| pgdc_5m              |  3806 |       10 |       20 |    5 |
| uk_lidar             |  1518 |       10 |       20 |    2 |
| ned_topobathy        |    35 |       12 |       20 |    3 |

**Comment by nvkelso** [comment]
Looks like one source is still at `min_zoom` **12**, but should be `min_zoom` **10** (maybe we updated this outside of the other update statement in the original issue?):

- `ned_topobathy` should be `min_zoom` **10**

Are these still **disabled**? 

- `mgg_greatlakes`
- `mgg_inundation_sandy`

Noting here that we're discussing this source in https://github.com/mojodna/marblecutter/issues/32#issuecomment-317065076 separately:

- `gmted` with `max_zoom` of **15** > ± 60°, else `max_zoom` of **10**

**Comment by iandees** [comment]
#### Disabled sources 

`mgg_greatlakes` and `mgg_inundation_sandy` are still disabled (I didn't re-build their footprints because they didn't have any footprint problems and we weren't using them).

#### ned_topobathy source

```
update footprints set min_zoom=10, max_zoom=20 where source='ned_topobathy';
UPDATE 35
```

**Comment by nvkelso** [comment]
Great, thanks!
