### ISSUE TITLE
Data shapes must match

### ISSUE THREAD

**Issue by iandees** [mojodna/marblecutter#40]
While looking for root cause on #39 I found a stack trace that looked like this:

```
File "/var/task/marblecutter/mosaic.py", line 76, in paste
window_data.shape, canvas.shape))

Exception: Data shapes must match: (1, 520, 264) != (1, 520, 520)
```

**Comment by mojodna** [comment]
Interesting. I have a theory, not particularly sound: upgrading to rasterio master resulted in "boundless" windows returning data that only covers the area where data exists. Pretty sure that it's a fatal exception though, rather than one that would just drop data.

It may also be related to top/bottom tiles (world-wise) or to the buffer-related tweaks (to reduce overall size when interpolating).

Next time you see this, see if you can figure out the tile coordinates responsible.

**Comment by iandees** [comment]
I should have been more specific there. The tile coordinates this shows up in are around the New York area that is referenced in #39. Around here:

https://terrain-lambda.dev.mapzen.com/hillshade/preview#13/40.6602/-74.0374

**Comment by mojodna** [comment]
/hillshade/13/2409/3082@2x.png produces this.

**Comment by mojodna** [comment]
Nope, just stupid bugs on my part (I was falsely assuming that horizontal and vertical buffers would always be the same).
