### ISSUE TITLE
Funky NED data with bad NODATA bathymetry values

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#8]
Affecting water bathymetry values off Marin Headlands.

@mojodna Can you add more details here, please? Is the fix to review the NED data and remove bad sources, or refetch from original data provider? 

<img width="380" alt="screen shot 2017-06-26 at 11 37 24" src="https://user-images.githubusercontent.com/853051/27554623-db131f3c-5a63-11e7-9718-8464148566f7.png">
<img width="637" alt="screen shot 2017-06-26 at 11 37 18" src="https://user-images.githubusercontent.com/853051/27554621-db038ef0-5a63-11e7-837c-cac0bd364f16.png">
<img width="925" alt="screen shot 2017-06-26 at 11 37 14" src="https://user-images.githubusercontent.com/853051/27554622-db0638f8-5a63-11e7-88f2-7b70dcaaed06.png">

**Comment by mojodna** [comment]
This area is covered by `ned19_n38x00_w122x75_ca_goldengate_2010` (NED), `ned19_n38x00_w122x75_ca_sanfrancisocoast_2010` (NED), and `ned19_n38x00_w122x75_ca_sanfrancisco_topobathy_2010` (NED topobathy).

1) is clipped by water, 2) is clipped by ???, 3) isn’t clipped

The fix is the sources similar to (2) should be removed, but I'm not sure how best to identify them.

(2) looks like this:

![image](https://user-images.githubusercontent.com/45/27554833-a480c3ce-5a64-11e7-816c-2105cd98ffc8.png)

**Comment by nvkelso** [comment]
Number 2 has "coast" in the file name. Are there others with that file name metadata?

**Comment by nvkelso** [comment]
This no longer seems to be a problem using either our endpoint or Seth's endpoint.

- Ours: https://k6yfeg1cx6.execute-api.us-east-1.amazonaws.com/Prod/normal/{z}/{x}/{y}.png
- Seth's: https://d34o1q5y1d9is8.cloudfront.net/normal/{z}/{x}/{y}.png

**What changed?**

At first I thought Seth's change in https://github.com/mojodna/marblecutter/issues/2 for the no-data spikes fixed his, but then checking ours it also seems cleaned up there (without the same fix).

**Comment by nvkelso** [comment]
Ours did have that fix, so might be because of that!

**Comment by nvkelso** [comment]
New footprint logic:

NED comes in earlier at same as bathymetry now, but bathy is prioritized (at default priority=0) over NED 1/9th (priority=1).

Software sorts by rounded resolution and then priority.
